#!/bin/sh

set -e

if [ "$1" = "purge" ]; then
   rm -rf /var/cache/squid-deb-proxy-desktop
   rm -rf /var/log/squid-deb-proxy-desktop
   rm -f /etc/squid-deb-proxy-desktop/squid-deb-proxy-desktop.conf
fi

#DEBHELPER#

